// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sausageshoot.proto

package SAUSAGE_SHOOT_OSS

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 玩家登陆
type PlayerLogin struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	PlatId               int64    `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`
	ZoneId               int64    `protobuf:"varint,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLogin) Reset()         { *m = PlayerLogin{} }
func (m *PlayerLogin) String() string { return proto.CompactTextString(m) }
func (*PlayerLogin) ProtoMessage()    {}
func (*PlayerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd25c59f2fd14d5, []int{0}
}

func (m *PlayerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLogin.Unmarshal(m, b)
}
func (m *PlayerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLogin.Marshal(b, m, deterministic)
}
func (m *PlayerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLogin.Merge(m, src)
}
func (m *PlayerLogin) XXX_Size() int {
	return xxx_messageInfo_PlayerLogin.Size(m)
}
func (m *PlayerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLogin proto.InternalMessageInfo

func (m *PlayerLogin) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerLogin) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PlayerLogin) GetPlatId() int64 {
	if m != nil {
		return m.PlatId
	}
	return 0
}

func (m *PlayerLogin) GetZoneId() int64 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

// 玩家登出
type PlayerLogout struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	PlatId               int64    `protobuf:"varint,3,opt,name=plat_id,json=platId,proto3" json:"plat_id,omitempty"`
	ZoneId               int64    `protobuf:"varint,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLogout) Reset()         { *m = PlayerLogout{} }
func (m *PlayerLogout) String() string { return proto.CompactTextString(m) }
func (*PlayerLogout) ProtoMessage()    {}
func (*PlayerLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd25c59f2fd14d5, []int{1}
}

func (m *PlayerLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLogout.Unmarshal(m, b)
}
func (m *PlayerLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLogout.Marshal(b, m, deterministic)
}
func (m *PlayerLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLogout.Merge(m, src)
}
func (m *PlayerLogout) XXX_Size() int {
	return xxx_messageInfo_PlayerLogout.Size(m)
}
func (m *PlayerLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLogout.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLogout proto.InternalMessageInfo

func (m *PlayerLogout) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerLogout) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PlayerLogout) GetPlatId() int64 {
	if m != nil {
		return m.PlatId
	}
	return 0
}

func (m *PlayerLogout) GetZoneId() int64 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

// 玩家通关
type PlayerPassMission struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	MissionId            int64    `protobuf:"varint,3,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerPassMission) Reset()         { *m = PlayerPassMission{} }
func (m *PlayerPassMission) String() string { return proto.CompactTextString(m) }
func (*PlayerPassMission) ProtoMessage()    {}
func (*PlayerPassMission) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd25c59f2fd14d5, []int{2}
}

func (m *PlayerPassMission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerPassMission.Unmarshal(m, b)
}
func (m *PlayerPassMission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerPassMission.Marshal(b, m, deterministic)
}
func (m *PlayerPassMission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerPassMission.Merge(m, src)
}
func (m *PlayerPassMission) XXX_Size() int {
	return xxx_messageInfo_PlayerPassMission.Size(m)
}
func (m *PlayerPassMission) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerPassMission.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerPassMission proto.InternalMessageInfo

func (m *PlayerPassMission) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerPassMission) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PlayerPassMission) GetMissionId() int64 {
	if m != nil {
		return m.MissionId
	}
	return 0
}

// 玩家升级
type PlayerLevelUp struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	From                 int64    `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLevelUp) Reset()         { *m = PlayerLevelUp{} }
func (m *PlayerLevelUp) String() string { return proto.CompactTextString(m) }
func (*PlayerLevelUp) ProtoMessage()    {}
func (*PlayerLevelUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd25c59f2fd14d5, []int{3}
}

func (m *PlayerLevelUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLevelUp.Unmarshal(m, b)
}
func (m *PlayerLevelUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLevelUp.Marshal(b, m, deterministic)
}
func (m *PlayerLevelUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLevelUp.Merge(m, src)
}
func (m *PlayerLevelUp) XXX_Size() int {
	return xxx_messageInfo_PlayerLevelUp.Size(m)
}
func (m *PlayerLevelUp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLevelUp.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLevelUp proto.InternalMessageInfo

func (m *PlayerLevelUp) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerLevelUp) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PlayerLevelUp) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *PlayerLevelUp) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

// 服务器心跳日志
type GameServerState struct {
	Time                 *Time    `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	GameIp               string   `protobuf:"bytes,2,opt,name=game_ip,json=gameIp,proto3" json:"game_ip,omitempty"`
	ZoneId               int64    `protobuf:"varint,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerState) Reset()         { *m = GameServerState{} }
func (m *GameServerState) String() string { return proto.CompactTextString(m) }
func (*GameServerState) ProtoMessage()    {}
func (*GameServerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fd25c59f2fd14d5, []int{4}
}

func (m *GameServerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerState.Unmarshal(m, b)
}
func (m *GameServerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerState.Marshal(b, m, deterministic)
}
func (m *GameServerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerState.Merge(m, src)
}
func (m *GameServerState) XXX_Size() int {
	return xxx_messageInfo_GameServerState.Size(m)
}
func (m *GameServerState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerState.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerState proto.InternalMessageInfo

func (m *GameServerState) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GameServerState) GetGameIp() string {
	if m != nil {
		return m.GameIp
	}
	return ""
}

func (m *GameServerState) GetZoneId() int64 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerLogin)(nil), "SAUSAGE_SHOOT_OSS.PlayerLogin")
	proto.RegisterType((*PlayerLogout)(nil), "SAUSAGE_SHOOT_OSS.PlayerLogout")
	proto.RegisterType((*PlayerPassMission)(nil), "SAUSAGE_SHOOT_OSS.PlayerPassMission")
	proto.RegisterType((*PlayerLevelUp)(nil), "SAUSAGE_SHOOT_OSS.PlayerLevelUp")
	proto.RegisterType((*GameServerState)(nil), "SAUSAGE_SHOOT_OSS.GameServerState")
}

func init() { proto.RegisterFile("sausageshoot.proto", fileDescriptor_4fd25c59f2fd14d5) }

var fileDescriptor_4fd25c59f2fd14d5 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0xb6, 0xf4, 0x4f, 0xa7, 0xfd, 0x2b, 0xdd, 0x4b, 0xab, 0x20, 0x94, 0x9c, 0x0a,
	0x42, 0x41, 0x7d, 0x82, 0x1e, 0xa4, 0x06, 0x94, 0x94, 0x6c, 0x7b, 0x0e, 0xab, 0x19, 0xe3, 0x42,
	0x36, 0xb3, 0x64, 0xb7, 0x05, 0x7d, 0x0c, 0x7d, 0x00, 0x7d, 0x54, 0xc9, 0x26, 0xd4, 0x82, 0x1e,
	0xbc, 0x14, 0xbc, 0x65, 0x32, 0xdf, 0xcc, 0xfc, 0xf8, 0xbe, 0x05, 0x6e, 0xe5, 0xc6, 0xca, 0x0c,
	0xed, 0x13, 0x91, 0x9b, 0x99, 0x92, 0x1c, 0xf1, 0xa1, 0x98, 0xaf, 0xc5, 0x7c, 0x71, 0x9d, 0x88,
	0x9b, 0x28, 0x5a, 0x25, 0x91, 0x10, 0xa7, 0x83, 0x07, 0xd2, 0x9a, 0x8a, 0x5a, 0x10, 0xbc, 0x33,
	0xe8, 0x2f, 0x73, 0xf9, 0x8c, 0xe5, 0x2d, 0x65, 0xaa, 0xe0, 0x17, 0xd0, 0x35, 0xbe, 0x1c, 0xb3,
	0x09, 0x9b, 0xf6, 0x2f, 0x4f, 0x66, 0xdf, 0x36, 0xcc, 0x6a, 0x7d, 0xdc, 0x08, 0xf9, 0x39, 0x74,
	0x9c, 0xd2, 0x38, 0x6e, 0xf9, 0x81, 0xd1, 0x0f, 0x03, 0x2b, 0xa5, 0x31, 0xf6, 0x22, 0x3e, 0x82,
	0x7f, 0x26, 0x97, 0x2e, 0x51, 0xe9, 0xb8, 0x3d, 0x61, 0xd3, 0xb6, 0xdf, 0xe2, 0xc2, 0xb4, 0x6a,
	0xbc, 0x50, 0x81, 0x55, 0xa3, 0x53, 0x37, 0xaa, 0x32, 0x4c, 0x83, 0x0f, 0x06, 0x83, 0x1d, 0x21,
	0x6d, 0xdc, 0x1f, 0x44, 0x7c, 0x65, 0x30, 0xac, 0x2f, 0x2e, 0xa5, 0xb5, 0x77, 0xca, 0x5a, 0x45,
	0x87, 0xb7, 0xf2, 0x0c, 0x40, 0xd7, 0xa7, 0xbe, 0x50, 0x7b, 0xcd, 0x9f, 0x30, 0x0d, 0xde, 0x18,
	0xfc, 0x6f, 0x7c, 0xc3, 0x2d, 0xe6, 0x6b, 0x73, 0x70, 0x20, 0x0e, 0x9d, 0xc7, 0x92, 0x74, 0x83,
	0xe2, 0xbf, 0xf9, 0x11, 0xb4, 0x1c, 0x35, 0x76, 0xb5, 0x1c, 0x05, 0x06, 0x8e, 0x17, 0x52, 0xa3,
	0xc0, 0x72, 0x8b, 0xa5, 0x70, 0xd2, 0xe1, 0xee, 0x06, 0xfb, 0x65, 0x38, 0x99, 0xd4, 0x98, 0x28,
	0xe3, 0x99, 0x7a, 0x71, 0xb7, 0x2a, 0x43, 0xb3, 0x1f, 0x4e, 0x7b, 0x3f, 0x9c, 0xfb, 0xae, 0x7f,
	0xe8, 0x57, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x20, 0x0c, 0xb1, 0x1f, 0x03, 0x00, 0x00,
}
